version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.6.3
    container_name: airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
    depends_on:
      - postgres
      - mongo
    ports:
      - "8080:8080"
    entrypoint: >
      /bin/bash -c "
      pip install --no-cache-dir pymongo && 
      airflow db init && 
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin && 
      airflow webserver"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
  
  airflow-scheduler:
    image: apache/airflow:2.6.3
    container_name: airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
    depends_on:
      - postgres
      - airflow-webserver
    entrypoint: >
      /bin/bash -c "
      pip install pymongo && 
      airflow db init && 
      airflow scheduler"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs


volumes:
  mongo_data:
  postgres-data: